controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    amr_controller:
      type: diff_drive_controller/DiffDriveController

amr_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: true
    velocity_command_topic: "/amr_controller/cmd_vel"

    left_wheel_names: ['wheel_left_joint']
    right_wheel_names: ['wheel_right_joint']

    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]

    wheel_separation: 0.322
    wheel_radius: 0.08

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Velocity commands timeout [s]
    cmd_vel_timeout: 0.5

    # Base frame_id
    base_frame_id: base_footprint

    # Publish limited velocity
    publish_limited_velocity: true

    # Publish wheel data
    publish_wheel_data: true

    # Publish to TF directly or not
    enable_odom_tf: true

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 3.1  # m/s
        min_velocity: -0.5 # m/s
        has_acceleration_limits: true
        max_acceleration: 0.8  # m/s²
        min_acceleration: -0.4 # m/s²
        has_jerk_limits: false
        max_jerk: 5.0  # m/s³
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.7  # rad/s
        has_acceleration_limits: true
        max_acceleration: 1.5  # rad/s²
        has_jerk_limits: false
        max_jerk: 2.5  # rad/s³

simple_velocity_controller:
  ros__parameters:
    joints:
      - wheel_left_joint
      - wheel_right_joint