/**:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: /cmd_vel_stamped
      deadman_buttons: [5]
      axis_mappings:
        twist-linear-x:
          axis: 5
          scale: 1.0 
          offset: 0.0
        twist-angular-z:
          axis: 2
          scale: 8.0
          offset: 0.0 
      stamp_header: true 