slam_toolbox:
  ros__parameters:
    use_sim_time: true
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping
    resolution: 0.05
    max_laser_range: 10.0
    transform_publish_period: 0.05
    map_publish_period: 1.0
    use_scan_matching: false
    enable_interactive_mode: true
    use_slam_mode: true
    queue_size: 10000
    tf_buffer_cache_time: 15.0
    transform_timeout: 2.5
    throttle_scans: 5
    laser_frame: laser_frame
    map_start_pose: [0.0, 0.0, 0.0]








